version: '2.3'
services:
  # object-detection-ssd-gpu:
  #   runtime: nvidia
  #   image: arruda/object-detection-service:${IMAGE_TAG}-gpu
  #   command: python /service/object_detection_service/run.py

  #   depends_on:
  #    - redis
  #   environment:
  #     - REDIS_ADDRESS=${REDIS_ADDRESS}
  #     - REDIS_PORT=${REDIS_PORT}
  #     - SERVICE_STREAM_KEY=${OBJECT_DETECTION_SSD_GPU_STREAM_KEY}
  #     - PUB_EVENT_TYPE_SERVICE_WORKER_ANNOUNCED=${EVENT_TYPE_SERVICE_WORKER_ANNOUNCED}
  #     - SERVICE_DETAILS_SERVICE_TYPE=ObjectDetection
  #     - SERVICE_DETAILS_CONTENT_TYPES=node_attribute:bounding_box,node_attribute:label,node_attribute:confidence,node:person,node:car
  #     - SERVICE_DETAILS_STREAM_KEY=${OBJECT_DETECTION_SSD_GPU_STREAM_KEY}
  #     - SERVICE_DETAILS_QUEUE_LIMIT=100
  #     - SERVICE_DETAILS_THROUGHPUT=34.33
  #     - SERVICE_DETAILS_ACCURACY=0.21
  #     - SERVICE_DETAILS_ENERGY_CONSUMPTION=163
  #     - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
  #     - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
  #     - PYTHONUNBUFFERED=0
  #     - CUDA_VISIBLE_DEVICES=0
  #     - GPU_SUPPORT_FLAG=1
  #     - DNN_TF_GPU_FRACTION=1.0
  #     - MODEL_NAME=ssd_mobilenet_v1_coco_2017_11_17
  #     - INPUT_WIDTH=300
  #     - INPUT_HEIGHT=300
  #     - DETECTION_THRESHOLD=0.5
  #     - ALLOW_MEMORY_GROWTH=True
  #     - LOGGING_LEVEL=${LOGGING_LEVEL}
  #     - SERVICE_REGISTRY_CMD_KEY=dontneed
  #     - SERVICE_CMD_KEY=dontneed
  # object-detection-ssd:
  #   image: arruda/object-detection-service:${IMAGE_TAG}
  #   command: python /service/object_detection_service/run.py

  #   depends_on:
  #    - redis
  #   environment:
  #     - REDIS_ADDRESS=${REDIS_ADDRESS}
  #     - REDIS_PORT=${REDIS_PORT}
  #     - SERVICE_STREAM_KEY=${OBJECT_DETECTION_SSD_STREAM_KEY}
  #     - PUB_EVENT_TYPE_SERVICE_WORKER_ANNOUNCED=${EVENT_TYPE_SERVICE_WORKER_ANNOUNCED}
  #     - SERVICE_DETAILS_SERVICE_TYPE=ObjectDetection
  #     - SERVICE_DETAILS_CONTENT_TYPES=node_attribute:bounding_box,node_attribute:label,node_attribute:confidence,node:person,node:car
  #     - SERVICE_DETAILS_STREAM_KEY=${OBJECT_DETECTION_SSD_STREAM_KEY}
  #     - SERVICE_DETAILS_QUEUE_LIMIT=100
  #     - SERVICE_DETAILS_THROUGHPUT=45.6
  #     - SERVICE_DETAILS_ACCURACY=0.21
  #     - SERVICE_DETAILS_ENERGY_CONSUMPTION=188
  #     - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
  #     - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
  #     - PYTHONUNBUFFERED=0
  #     - CUDA_VISIBLE_DEVICES=-1
  #     - GPU_SUPPORT_FLAG=0
  #     - MODEL_NAME=ssd_mobilenet_v1_coco_2017_11_17
  #     - INPUT_WIDTH=300
  #     - INPUT_HEIGHT=300
  #     - DETECTION_THRESHOLD=0.5
  #     - ALLOW_MEMORY_GROWTH=True
  #     - LOGGING_LEVEL=${LOGGING_LEVEL}
  #     - SERVICE_REGISTRY_CMD_KEY=dontneed
  #     - SERVICE_CMD_KEY=dontneed

  # object-detection-ssd-gpu:
  #   runtime: nvidia
  #   image: arruda/object-detection-service:${IMAGE_TAG}-gpu
  #   command: python /service/object_detection_service/run.py

  #   depends_on:
  #    - redis
  #   environment:
  #     - REDIS_ADDRESS=${REDIS_ADDRESS}
  #     - REDIS_PORT=${REDIS_PORT}
  #     - SERVICE_STREAM_KEY=${OBJECT_DETECTION_SSD_GPU_STREAM_KEY}
  #     - PUB_EVENT_TYPE_SERVICE_WORKER_ANNOUNCED=${EVENT_TYPE_SERVICE_WORKER_ANNOUNCED}
  #     - SERVICE_DETAILS_SERVICE_TYPE=ObjectDetection
  #     - SERVICE_DETAILS_CONTENT_TYPES=node_attribute:bounding_box,node_attribute:label,node_attribute:confidence,node:hat,node:not_hat
  #     - SERVICE_DETAILS_STREAM_KEY=${OBJECT_DETECTION_SSD_GPU_STREAM_KEY}
  #     - SERVICE_DETAILS_QUEUE_LIMIT=100
  #     - SERVICE_DETAILS_THROUGHPUT=34.33
  #     - SERVICE_DETAILS_ACCURACY=0.21
  #     - SERVICE_DETAILS_ENERGY_CONSUMPTION=163
  #     - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
  #     - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
  #     - PYTHONUNBUFFERED=0
  #     - CUDA_VISIBLE_DEVICES=0
  #     - GPU_SUPPORT_FLAG=1
  #     - DNN_TF_GPU_FRACTION=0.75
  #     - MODEL_NAME=hat_not_hat
  #     - MODEL_TYPE=yolov3
  #     - INPUT_WIDTH=300
  #     - INPUT_HEIGHT=300
  #     - DETECTION_THRESHOLD=0.6
  #     - ALLOW_MEMORY_GROWTH=True
  #     - LOGGING_LEVEL=${LOGGING_LEVEL}
  #     - SERVICE_REGISTRY_CMD_KEY=dontneed
  #     - SERVICE_CMD_KEY=dontneed
  object-detection-yolo:
    image: arruda/pytorch-object-detection-service:${IMAGE_TAG}
    command: python /service/pytorch_object_detection_service/run.py

    depends_on:
      - redis
      - adaptation-planner
      - adaptation-monitor
      - adaptation-analyser
      - client-manager

    environment:
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_STREAM_KEY=${OBJECT_DETECTION_YOLO_STREAM_KEY}
      - PUB_EVENT_TYPE_SERVICE_WORKER_ANNOUNCED=${EVENT_TYPE_SERVICE_WORKER_ANNOUNCED}
      - SERVICE_DETAILS_SERVICE_TYPE=ObjectDetection
      - SERVICE_DETAILS_CONTENT_TYPES=node_attribute:bounding_box,node_attribute:label,node_attribute:confidence,node:person,node:car
      - SERVICE_DETAILS_STREAM_KEY=${OBJECT_DETECTION_YOLO_STREAM_KEY}
      - SERVICE_DETAILS_QUEUE_LIMIT=100
      - SERVICE_DETAILS_THROUGHPUT=34.33
      - SERVICE_DETAILS_ACCURACY=0.21
      - SERVICE_DETAILS_ENERGY_CONSUMPTION=163
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - PYTHONUNBUFFERED=0
      - DETECTION_THRESHOLD=0.5
      - OBJ_MODEL_NAME=yolov5n
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - SERVICE_REGISTRY_CMD_KEY=dontneed
      - SERVICE_CMD_KEY=dontneed

  image-resizer:
    runtime: nvidia
    image: arruda/image-resizer-service:master
    command: python3 image_resizer_service/run.py

    depends_on:
      - redis
      - adaptation-planner
      - adaptation-monitor
      - adaptation-analyser
      - client-manager

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${IMAGE_RESIZER_STREAM_KEY}
      - PUB_EVENT_TYPE_SERVICE_WORKER_ANNOUNCED=${EVENT_TYPE_SERVICE_WORKER_ANNOUNCED}
      - SERVICE_DETAILS_SERVICE_TYPE=ImageResizer
      - SERVICE_DETAILS_CONTENT_TYPES=none
      - SERVICE_DETAILS_STREAM_KEY=${IMAGE_RESIZER_STREAM_KEY}
      - SERVICE_DETAILS_QUEUE_LIMIT=100
      - SERVICE_DETAILS_THROUGHPUT=100
      - SERVICE_DETAILS_ACCURACY=1
      - SERVICE_DETAILS_ENERGY_CONSUMPTION=10
      - RESIZE_METHOD=${RESIZE_METHOD}
      - RESIZE_SCALE=4